In [1]:
def normalize(X):
    for i in range(X.shape[1]):
        X[:,i] = (X[:,i] - X[:,i].mean())/X[:,i].std()
    return X

In [2]:

# from sklearn import tree
import pandas as pd
import numpy as np
def get_data():
    """
    Returns the data from the xlsx file
    """
    file_name = 'yeast.csv' 
    df = pd.read_csv(file_name, index_col=None)
    # print(df.head()) # print the first 5 rows
    return df

C = 10

D = 8
# p = 8

md = get_data()


# drop the 0 column
# ?????????
md = md.drop(columns=['DBName'])

md.dropna(inplace = True)
# print(md.shape)
md.replace('?', 0, inplace = True)

print(md.head(10))

# print(md[0 : 1])

#print(columns[1])


      1     2     3     4    5    6     7     8 OutName
0  0.58  0.61  0.47  0.13  0.5  0.0  0.48  0.22     MIT
1  0.43  0.67  0.48  0.27  0.5  0.0  0.53  0.22     MIT
2  0.64  0.62  0.49  0.15  0.5  0.0  0.53  0.22     MIT
3  0.58  0.44  0.57  0.13  0.5  0.0  0.54  0.22     NUC
4  0.42  0.44  0.48  0.54  0.5  0.0  0.48  0.22     MIT
5  0.51  0.40  0.56  0.17  0.5  0.5  0.49  0.22     CYT
6  0.50  0.54  0.48  0.65  0.5  0.0  0.53  0.22     MIT
7  0.48  0.45  0.59  0.20  0.5  0.0  0.58  0.34     NUC
8  0.55  0.50  0.66  0.36  0.5  0.0  0.49  0.22     MIT
9  0.40  0.39  0.60  0.15  0.5  0.0  0.58  0.30     CYT


Convert continuous data to categorical one

In [3]:
noOfBins = 20
# print(md['DBName'])
# print(md.columns)
# print(md['1'])
for i in range(D):
    md["cat" + str(i + 1)] = pd.cut(md[str(i+1)].values, bins=noOfBins, labels= range(0, noOfBins))
md.drop(columns=['1', '2', '3', '4', '5', '6', '7', '8'], inplace=True)
last_column = md.pop('OutName')
md.insert(8, 'OutName', last_column)
md.head(20)
# gk = md.groupby('Outname')
# print(md[1].value_counts())


cat1 cat2 cat3 cat4 cat5 cat6 cat7 cat8 OutName
0    10   11    6    2    0    0   13    4     MIT
1     7   12    6    5    0    0   14    4     MIT
2    11   11    7    2    0    0   14    4     MIT
3    10    7    9    2    0    0   14    4     NUC
4     6    7    6   10    0    0   13    4     MIT
5     8    6    8    3    0   12   13    4     CYT
6     8    9    6   12    0    0   14    4     MIT
7     8    7    9    3    0    0   15    6     NUC
8     9    8   11    7    0    0   13    4     MIT
9     6    5    9    2    0    0   15    5     CYT
10    7    5    8    4    0    0   14    5     NUC
11    6    5    9    3    0    0   14    5     NUC
12    6    6    9    6    0    0   14    4     CYT
13   11    6    7    9    0    0   14    4     MIT
14   12    9    6    3    0    0   12    4     MIT
15    7    7    7    2    0    0   13    4     CYT
16    8    5    7    2    0    0   13    7     CYT
17   10    7    8    2    0    0   13    5     NUC
18    8    4    8    4    0    0   13    4     NUC
19   11   10    8    4    0    0   13    4     NUC

In [4]:
X = md.iloc[:, 0:8].values.reshape(-1, 8)
outputs = ['CYT', 'NUC', 'MIT', 'ME3', 'ME2', 'ME1', 'EXC', 'VAC', 'POX', 'ERL']

# add 1 to the first column
# X = np.insert(X, 0, 1, axis=1)
# np.random.shuffle(X)

print('X:', X)
print(X.shape)

# X = normalize(X)
# print(X)


M = X.shape[0]
Y = md.iloc[:, 8:9].values.reshape(-1, 1)

X: [[10 11 6 ... 0 13 4]
 [7 12 6 ... 0 14 4]
 [11 11 7 ... 0 14 4]
 ...
 [12 10 3 ... 0 15 4]
 [7 6 9 ... 0 14 7]
 [12 9 8 ... 0 14 4]]
(1484, 8)


In [5]:
y = np.zeros(len(Y))

for i in range(len(Y)):
    y[i] = outputs.index(Y[i][0])


In [6]:
ncValues = np.zeros(C)
piValues = []

for i in range(M):
    ncValues[int(y[i])] += 1
for c in range(C):
    piValues.append(ncValues[c]/M)
print(sum(piValues))

# md.dtypes
md[['cat1', 'cat2', 'cat3', 'cat4', 'cat5', 'cat6', 'cat7', 'cat8']] = md[['cat1', 'cat2', 'cat3', 'cat4', 'cat5', 'cat6', 'cat7', 'cat8']].astype(int)

data_mod = md.groupby(['OutName']).sum()


# data_no_out = md.drop(columns=['OutName'])
# total_data_per_class = data_no_out.sum()

axisSum = data_mod.sum(axis=1)

theta = []
alpha = 0.01

for d in range(D):
    theta.append((data_mod['cat' + str(d + 1)] + alpha )/ (axisSum + alpha*D))

# print('sum ',data_mod.sum(axis=1))
# axes = md.axes
# columns = md.columns

for i in range(D):
    print(sum(theta[i]))


# theta_dic = theta.to_dict()
# print(theta_dic)

1.0
1.984228231904708
1.8865306356775229
1.1964115817510232
0.9420746633100909
0.2554230605076929
0.17991581449109714
2.6232966112790006
0.9321194010788647


In [7]:
# make prediction
md_dic = md.to_dict()
# print(md_dic)
# for d in range(D):
#     print(np.log(1 + md_dic['cat' + str(d + 1)][0]))

testSet = X
prediction = np.zeros(len(testSet))

# prediction[0] = 'asd'
for i in range(len(testSet)): 
    prbAllClass = np.zeros(C)
    for c in range(C):
        prbAllClass[c] = np.log(piValues[c])
        for d in range(D):
            # first = md_dic['cat' + str(d + 1)][i]
            
            first = np.log(1 + md_dic['cat' + str(d + 1)][i])
            second = np.log(theta[d][c]) # ['cat' + str(d + 1)][outputs[c]])
            
            prbAllClass[c] += first * second
            # print( i, prbAllClass[c], first, second)
    print(prbAllClass)
    prediction[i] = np.argmax(prbAllClass)


print("accuracy: ", (prediction == y[:len(testSet)]).sum()/len(testSet))

[-22.82331617 -26.38121539 -23.52129708 -24.44283696 -25.32655384
 -25.51629404 -25.53727982 -25.54472259 -28.23925358 -27.32908856]
[-24.18201292 -27.89213047 -24.92299936 -25.81652312 -26.72806811
 -26.80543103 -26.5293797  -26.87632785 -29.65702941 -28.82695455]
[-23.294044   -26.97804738 -24.02644262 -25.02227445 -25.85681139
 -26.07260791 -26.03860281 -26.02735344 -28.77655629 -27.82169608]
[-22.79651496 -26.69396343 -23.78831762 -24.94520585 -25.62095942
 -25.79322593 -25.61042982 -25.50826278 -28.30074747 -27.45816679]
[-24.4547116  -28.28629353 -25.35520521 -26.2491078  -27.08552284
 -27.13815911 -26.51161283 -27.11076887 -29.91826478 -29.28417432]
[-41.75573196 -53.65891107 -54.85620765 -56.6350815  -57.47406253
 -59.92109571 -39.38346684 -62.44052712 -32.55225406 -57.70788464]
[-25.78959337 -29.6404823  -26.52302006 -27.38161105 -28.2671757
 -28.42911209 -27.74934741 -28.47891919 -31.3357898  -30.57202114]
[-23.98462085 -28.18452852 -25.14873    -26.25073207 -26.92951363
 -26

In [8]:
# from sklearn.model_selection import train_test_split
# from sklearn.naive_bayes import ComplementNB

# X_train, X_test, Y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
# gnb = ComplementNB()
# gnb.fit(X_train, Y_train)
# y_pred = gnb.predict(X_test)
# print("Number of mislabeled points out of a total %d points : %d"
#       % (X_test.shape[0], (y_test != y_pred).sum()))

# from sklearn import metrics

# # Model Accuracy, how often is the classifier correct?
# print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

In [9]:
# from sklearn.naive_bayes import MultinomialNB
# from sklearn.model_selection import train_test_split
# X_train, X_test, Y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=0)
# gnb = MultinomialNB()
# gnb.fit(X_train, Y_train)
# y_pred = gnb.predict(X_test)
# print("Number of mislabeled points out of a total %d points : %d"
#       % (X_test.shape[0], (y_test != y_pred).sum()))
# print('pred: ', y_pred, '\n# of 0 predicts: ', sum(y_pred == 0))
# from sklearn import metrics

# # Model Accuracy, how often is the classifier correct?
# print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
